# Generated by Django 3.0.3 on 2020-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=50, unique=True)),
                ('userPass', models.CharField(max_length=30)),
                ('userBirth', models.DateField()),
                ('userSex', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'userInfoTable',
            },
        ),
    ]
