# Generated by Django 3.0.3 on 2020-04-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.BigAutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('productImg', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userAccount', models.CharField(max_length=50, unique=True)),
                ('userPass', models.CharField(max_length=30)),
                ('userBirth', models.DateTimeField(auto_now=True)),
                ('userSex', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'userInfoTable',
            },
        ),
        migrations.CreateModel(
            name='UserGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp01.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myapp01.UserInfo')),
            ],
            options={
                'db_table': 'userGoods',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('orderMon', models.DecimalField(decimal_places=2, max_digits=11)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp01.UserInfo')),
            ],
            options={
                'db_table': 'order_Table',
            },
        ),
    ]
