# Generated by Django 3.0.3 on 2020-04-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userBirth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('orderMon', models.DecimalField(decimal_places=2, max_digits=11)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp01.UserInfo')),
            ],
            options={
                'db_table': 'order_Table',
            },
        ),
    ]
