# Generated by Django 3.0.3 on 2020-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp01', '0002_auto_20200401_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userId',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
